declare module "lucide-react" {
  import type { ComponentType, SVGProps } from "react";

  export type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;
  export const Activity: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Building2: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Copy: LucideIcon;
  export const Download: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Inbox: LucideIcon;
  export const LogOut: LucideIcon;
  export const LoaderCircle: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const Lock: LucideIcon;
  export const MapPin: LucideIcon;
  export const Menu: LucideIcon;
  export const Mic: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const PanelsTopLeft: LucideIcon;
  export const Plus: LucideIcon;
  export const Printer: LucideIcon;
  export const QrCode: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Star: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Store: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Upload: LucideIcon;
  export const UserRound: LucideIcon;
  export const X: LucideIcon;
}
