"use client";

import { useState, useTransition } from "react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/browser";
import { normalizeGoogleReviewUrl } from "@/lib/security/google-url";
import { saveOnboardingProgressAction, completeOnboardingAction } from "@/features/onboarding/server/actions";
import { OnboardingStepper } from "@/components/onboarding/onboarding-stepper";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { PlanKey } from "@/config/plans";

type Data = { name: string; category: string; description: string; services: string; phone: string; email: string; website: string; addressLine: string; city: string; state: string; country: string; googleReviewUrl: string; defaultLanguage: string; brandColor: string; logoUrl: string; headline: string; lowRatingMessage: string; tags: string; contactFields: string; posterTemplate: "light" | "dark" };
const defaults: Data = { name: "", category: "", description: "", services: "", phone: "", email: "", website: "", addressLine: "", city: "", state: "", country: "", googleReviewUrl: "", defaultLanguage: "en", brandColor: "#2563eb", logoUrl: "", headline: "Share what your visit was really like", lowRatingMessage: "We welcome honest feedback and will follow up when you choose to share contact details.", tags: "Service\nProduct quality\nCommunication", contactFields: "name,email", posterTemplate: "light" };

export function OnboardingWizard({ ownerId, planKey, initial }: { ownerId: string; planKey: PlanKey; initial?: { current_step: number; completed_steps: number[]; draft_data: unknown } | null }) {
  const [pending, startTransition] = useTransition(); const [step, setStep] = useState(initial?.current_step ?? 1); const [completed, setCompleted] = useState<number[]>(initial?.completed_steps ?? []); const [data, setData] = useState<Data>({ ...defaults, ...(typeof initial?.draft_data === "object" && initial?.draft_data ? initial.draft_data as Partial<Data> : {}) });
  const update = (key: keyof Data, value: string) => setData((current) => ({ ...current, [key]: value }));
  function persist(nextStep: number, nextCompleted = completed) { startTransition(async () => { try { await saveOnboardingProgressAction({ currentStep: nextStep, completedSteps: nextCompleted, draftData: data }); setStep(nextStep); setCompleted(nextCompleted); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save progress."); } }); }
  function next() { const nextCompleted = [...new Set([...completed, step])]; persist(Math.min(6, step + 1), nextCompleted); }
  function back() { persist(Math.max(1, step - 1)); }
  async function testGoogleLink() { try { const url = normalizeGoogleReviewUrl(data.googleReviewUrl); window.open(url, "_blank", "noopener,noreferrer"); toast.success("Google link opened in a new tab."); } catch (error) { toast.error(error instanceof Error ? error.message : "Enter a valid Google link."); } }
  async function uploadLogo(file: File) { const supabase = createClient(); const path = `${ownerId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "")}`; const { error } = await supabase.storage.from("business-logos").upload(path, file, { upsert: false, contentType: file.type }); if (error) { toast.error(error.message); return; } const { data: url } = supabase.storage.from("business-logos").getPublicUrl(path); update("logoUrl", url.publicUrl); toast.success("Logo uploaded."); }
  function publish() { startTransition(async () => { try { await completeOnboardingAction({ ...data, ownerFullName: undefined }); } catch (error) { toast.error(error instanceof Error ? error.message : "Complete each required field before publishing."); } }); }
  return <div className="space-y-6"><OnboardingStepper currentStep={step} completedSteps={completed} /><div className="rounded-2xl border bg-card p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-primary">Step {step} of 6</p><h1 className="mt-1 text-2xl font-semibold">{["Confirm payment", "Set up your location", "Connect Google", "Shape the experience", "Make it yours", "Test and publish"][step - 1]}</h1></div><span className="rounded-full bg-muted px-3 py-1 text-xs font-medium capitalize">{planKey} plan</span></div>
    {step === 1 ? <div className="mt-8 space-y-4"><p className="text-muted-foreground">Your subscription is active. This step is confirmed by the server and cannot be skipped.</p><div className="rounded-xl bg-primary/5 p-4 text-sm">Paid access unlocks your business workspace, QR publishing and grounded AI generation.</div></div> : null}
    {step === 2 ? <div className="mt-8 grid gap-4 sm:grid-cols-2"><Field label="Business name" value={data.name} onChange={(value) => update("name", value)} required /><Field label="Category" value={data.category} onChange={(value) => update("category", value)} required /><Field label="Phone" value={data.phone} onChange={(value) => update("phone", value)} /><Field label="Email" value={data.email} onChange={(value) => update("email", value)} type="email" /><Field label="Website" value={data.website} onChange={(value) => update("website", value)} type="url" /><Field label="Address" value={data.addressLine} onChange={(value) => update("addressLine", value)} /><Field label="City" value={data.city} onChange={(value) => update("city", value)} /><Field label="State" value={data.state} onChange={(value) => update("state", value)} /><Field label="Country" value={data.country} onChange={(value) => update("country", value)} /><div className="sm:col-span-2"><Label htmlFor="description">Description</Label><Textarea id="description" className="mt-2" value={data.description} onChange={(event) => update("description", event.target.value)} /></div></div> : null}
    {step === 3 ? <div className="mt-8 space-y-4"><div><Label htmlFor="googleReviewUrl">Official Google review link</Label><Input id="googleReviewUrl" type="url" className="mt-2" value={data.googleReviewUrl} onChange={(event) => update("googleReviewUrl", event.target.value)} placeholder="https://g.page/.../review" /><p className="mt-2 text-sm text-muted-foreground">In Google Business Profile, choose Ask for reviews, copy the link, and paste it here. ReviewFlow accepts official Google destinations only.</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={testGoogleLink}>Test link</Button><Button type="button" variant="ghost" onClick={() => window.open("https://support.google.com/business/answer/7035772", "_blank", "noopener,noreferrer")}>How to find the link</Button></div></div> : null}
    {step === 4 ? <div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Label htmlFor="services">Products or services</Label><Textarea id="services" className="mt-2" value={data.services} onChange={(event) => update("services", event.target.value)} placeholder="One product or service per line" /></div><div className="sm:col-span-2"><Label htmlFor="tags">Experience tags</Label><Textarea id="tags" className="mt-2" value={data.tags} onChange={(event) => update("tags", event.target.value)} /></div><Field label="Default language" value={data.defaultLanguage} onChange={(value) => update("defaultLanguage", value)} /><div><Label htmlFor="lowRatingMessage">Low-rating support message</Label><Textarea id="lowRatingMessage" className="mt-2" value={data.lowRatingMessage} onChange={(event) => update("lowRatingMessage", event.target.value)} /></div><div><Label htmlFor="contactFields">Optional contact fields</Label><Input id="contactFields" className="mt-2" value={data.contactFields} onChange={(event) => update("contactFields", event.target.value)} placeholder="name,email,phone" /><p className="mt-1 text-xs text-muted-foreground">Comma-separated. Contact data is never sent to the AI assistant.</p></div></div> : null}
    {step === 5 ? <div className="mt-8 grid gap-6 lg:grid-cols-2"><div className="space-y-4"><div><Label htmlFor="logo">Logo upload</Label><Input id="logo" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="mt-2" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadLogo(file); }} /><p className="mt-2 text-xs text-muted-foreground">Stored in your Supabase Storage business-logos bucket.</p></div><Field label="Brand colour" value={data.brandColor} onChange={(value) => update("brandColor", value)} type="color" /><Field label="Poster headline" value={data.headline} onChange={(value) => update("headline", value)} /><div><Label htmlFor="posterTemplate">QR poster template</Label><select id="posterTemplate" className="mt-2 h-10 w-full rounded-md border bg-card px-3 text-sm" value={data.posterTemplate} onChange={(event) => update("posterTemplate", event.target.value as "light" | "dark")}><option value="light">Light</option><option value="dark">Dark</option></select></div></div><div className="rounded-2xl border p-5" style={{ borderColor: data.brandColor }}><p className="text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground">Public preview</p><div className="mt-8 text-center"><div className="mx-auto h-24 w-24 rounded-xl bg-muted" /><h2 className="mt-5 text-xl font-semibold">{data.name || "Your business"}</h2><p className="mt-2 text-sm text-muted-foreground">{data.headline}</p></div></div></div> : null}
    {step === 6 ? <div className="mt-8 space-y-5"><div className="rounded-xl border p-4"><p className="font-medium">Test checklist</p><ul className="mt-3 space-y-2 text-sm text-muted-foreground"><li>✓ Paid subscription confirmed</li><li>✓ Google link validated before saving</li><li>✓ QR campaign will be created with the business</li><li>✓ Customers will always open Google manually</li></ul></div><Button type="button" variant="outline" onClick={() => window.open(`/r/${data.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, "_blank", "noopener,noreferrer")}>Open safe test preview</Button></div> : null}
    <div className="mt-8 flex flex-wrap justify-between gap-3 border-t pt-5">{step > 1 ? <Button type="button" variant="outline" onClick={back} disabled={pending}>Back</Button> : <span />}{step < 6 ? <Button type="button" onClick={next} disabled={pending || (step === 2 && (!data.name || !data.category)) || (step === 3 && !data.googleReviewUrl)}>{pending ? "Saving…" : "Save and continue"}</Button> : <Button type="button" onClick={publish} disabled={pending}>{pending ? "Publishing…" : "Publish business and open dashboard"}</Button>}</div></div></div>;
}

function Field({ label, value, onChange, type = "text", required }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <div><Label htmlFor={label}>{label}{required ? " *" : ""}</Label><Input id={label} type={type} required={required} className="mt-2" value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
